CREATE TABLE TB_PRODUTO(
    ID_PRODUTO int not null primary key IDENTITY(1,1),
	NM_PRODUTO VARCHAR(200) NOT NULL,
	VL_PRODUTO NUMERIC(8,2) NOT NULL,
	DS_DESCRICAO VARCHAR(400) NOT NULL,
	QT_PRODUTO INT NOT NULL,
	DT_INSERCAO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
);